### ISSUE TITLE
Nova LXD cannot upload images to LXD. Fails with "unsupported compression" errors.

### ISSUE THREAD

**Issue by fawadkhaliq** [lxc/nova-lxd#110]
Nova LXD cannot upload images to LXD. Fails with "unsupported compression" errors.

Ubuntu 15.10, DevStack Mitaka/master code base. 

2016-03-02 17:12:23.275 ERROR nova.compute.manager [req-b9bb0dfa-1dbb-44bf-b54e-cdcd979a5e5b admin alt_demo] [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d] Instance failed to spawn
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d] Traceback (most recent call last):
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/opt/stack/nova/nova/compute/manager.py", line 2193, in _build_resources
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     yield resources
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/opt/stack/nova/nova/compute/manager.py", line 2039, in _build_and_run_instance
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     block_device_info=block_device_info)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/opt/stack/nova-lxd/nova_lxd/nova/virt/lxd/driver.py", line 114, in spawn
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     network_info, block_device_info)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/opt/stack/nova-lxd/nova_lxd/nova/virt/lxd/operations.py", line 142, in spawn
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     self.destroy(context, instance, network_info)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     self.force_reraise()
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     six.reraise(self.type_, self.value, self.tb)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/opt/stack/nova-lxd/nova_lxd/nova/virt/lxd/operations.py", line 122, in spawn
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     self._fetch_image(context, instance, image_meta)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/opt/stack/nova-lxd/nova_lxd/nova/virt/lxd/operations.py", line 162, in _fetch_image
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     'ex': ex}, instance=instance)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     self.force_reraise()
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     six.reraise(self.type_, self.value, self.tb)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/opt/stack/nova-lxd/nova_lxd/nova/virt/lxd/operations.py", line 155, in _fetch_image
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     self.image.setup_image(context, instance, image_meta)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/opt/stack/nova-lxd/nova_lxd/nova/virt/lxd/image.py", line 110, in setup_image
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     self._cleanup_image(instance)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     self.force_reraise()
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     six.reraise(self.type_, self.value, self.tb)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/opt/stack/nova-lxd/nova_lxd/nova/virt/lxd/image.py", line 96, in setup_image
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     self._image_upload(instance)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/opt/stack/nova-lxd/nova_lxd/nova/virt/lxd/image.py", line 255, in _image_upload
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     headers=headers, instance=instance)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]   File "/opt/stack/nova-lxd/nova_lxd/nova/virt/lxd/session.py", line 624, in image_upload
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d]     raise exception.NovaException(msg)
2016-03-02 17:12:23.275 TRACE nova.compute.manager [instance: 7a7ee316-c951-4fc0-82bd-b378f64b963d] NovaException: Failed to communicate with LXD API 17ea90f8-e6a5-47df-9c85-e9287902edea:Error 500 - Unsupported compression..

**Comment by fawadkhaliq** [comment]
Images tried: vivid-server-cloudimg-amd64-root.tar.gz, wily-server-cloudimg-amd64-root.tar.xz, xenial-server-cloudimg-amd64-root.tar.xz, trusty-server-cloudimg-amd64-root.tar.gz

**Comment by zulcss** [comment]
Make sure that the images disk-format is either root-tar or raw and make sure you use the following image: http://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-am
