### ISSUE TITLE
Configdrive failure

### ISSUE THREAD

**Issue by zulcss** [lxc/nova-lxd#119]
Instances with configdrive attach fail to boot:

[ 8189.897706] cloud-init[325]: Traceback (most recent call last):
[ 8189.897955] cloud-init[325]:   File "/usr/bin/cloud-init", line 668, in <module>
[ 8189.898121] cloud-init[325]:     sys.exit(main())
[ 8189.898280] cloud-init[325]:   File "/usr/bin/cloud-init", line 664, in main
[ 8189.898433] cloud-init[325]:     get_uptime=True, func=functor, args=(name, args))
[ 8189.898585] cloud-init[325]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2040, in log_time
[ 8189.898738] cloud-init[325]:     ret = func(*args, **kwargs)
[ 8189.898890] cloud-init[325]:   File "/usr/bin/cloud-init", line 469, in status_wrapper
[ 8189.899040] cloud-init[325]:     util.ensure_dirs((data_d, link_d,))
[ 8189.899189] cloud-init[325]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1376, in ensure_dirs
[ 8189.900470] cloud-init[325]:     ensure_dir(d, mode)
[ 8189.901480] cloud-init[325]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1415, in ensure_dir
[ 8189.901846] cloud-init[325]:     chmod(path, mode)
[ 8189.901996] cloud-init[325]:   File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 1628, in chmod
[ 8189.902152] cloud-init[325]:     os.chmod(path, real_mode)
[ 8189.902300] cloud-init[325]: PermissionError: [Errno 1] Operation not permitted: '/var/lib/cloud/data'

**Comment by zulcss** [comment]
This is due to incorrect permissions in the container for the directory.
