### ISSUE TITLE
n-cpu service failed to start due to "no module named lxd"

### ISSUE THREAD

**Issue by yf13** [lxc/nova-lxd#146]
Hi,

I am trying "stable/mitaka" version of devstack on Ubuntu14.04 LTS virtual machine with nova-lxd plugin enabled.

however, the devstack can't start due to errors in n-cpu.log:

```
" | tee "/opt/stack/status/stack/n-cpu.failure"fg || echo "n-cpu failed to start 
[1] 24176
/usr/local/bin/nova-compute --config-file /etc/nova/nova.conf
2016-06-01 11:09:22.933 24176 WARNING oslo_reports.guru_meditation_report [-] Guru mediation now registers SIGUSR1 and SIGUSR2 by default for backward compatibility. SIGUSR1 will no longer be registered in a future release, so please use SIGUSR2 to generate reports.
2016-06-01 11:09:23.129 24176 INFO nova.virt.driver [-] Loading compute driver 'lxd.LXDDriver'
2016-06-01 11:09:23.129 24176 ERROR nova.virt.driver [-] Unable to load the virtualization driver
2016-06-01 11:09:23.129 24176 ERROR nova.virt.driver Traceback (most recent call last):
2016-06-01 11:09:23.129 24176 ERROR nova.virt.driver   File "/m/u/stack/nova/nova/virt/driver.py", line 1622, in load_compute_driver
2016-06-01 11:09:23.129 24176 ERROR nova.virt.driver     virtapi)
2016-06-01 11:09:23.129 24176 ERROR nova.virt.driver   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/importutils.py", line 64, in import_object_ns
2016-06-01 11:09:23.129 24176 ERROR nova.virt.driver     cls = import_class(import_str)
2016-06-01 11:09:23.129 24176 ERROR nova.virt.driver   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/importutils.py", line 30, in import_class
2016-06-01 11:09:23.129 24176 ERROR nova.virt.driver     __import__(mod_str)
2016-06-01 11:09:23.129 24176 ERROR nova.virt.driver ImportError: No module named lxd
2016-06-01 11:09:23.129 24176 ERROR nova.virt.driver 
n-cpu failed to start

```

Here is the content of my local.conf:

```
u@u14 ~/devstack:$ cat local.conf | grep -v -e "^[ ]*$" -e "^[ ]*#"
[[local|localrc]]
DEST=/opt/stack
LOGDIR=$DEST/logs
ADMIN_PASSWORD=nomoresecret
DATABASE_PASSWORD=stackdb
RABBIT_PASSWORD=stackqueue
SERVICE_PASSWORD=$ADMIN_PASSWORD
LOGFILE=$DEST/logs/stack.sh.log
LOGDAYS=2
LOG_COLOR=False
ENABLE_IDENTITY_V2=False
CINDER_BRANCH=stable/mitaka
GLANCE_BRANCH=stable/mitaka
HORIZON_BRANCH=stable/mitaka
KEYSTONE_BRANCH=stable/mitaka
KEYSTONECLIENT_BRANCH=stable/mitaka
NOVA_BRANCH=stable/mitaka
NOVACLIENT_BRANCH=stable/mitaka
NEUTRON_BRANCH=stable/mitaka
SWIFT_BRANCH=stable/mitaka
SWIFT_HASH=66a3d6b56c1f479c8b4e70ab5c2000f5
SWIFT_REPLICAS=1
SWIFT_DATA_DIR=$DEST/data
enable_plugin nova-lxd https://github.com/lxc/nova-lxd
disable_service heat h-api h-api-cfn h-api-cw h-eng
disable_service cinder c-api c-vol c-sch
disable_service tempest
```

Here is the dump file: 
[worlddump-2016-06-01-030955.txt](https://github.com/lxc/nova-lxd/files/292591/worlddump-2016-06-01-030955.txt)

Can someone help to see what is wrong here?

Regards,
yanfeng

**Comment by rockstar** [comment]
Are you using the tip of devstack and tip of nova with stable/mitaka?

**Comment by dakshi5** [comment]
This may be because you haven't initialized LXD on the host/or added to the group.
